name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:

    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.12 # Define the elixir version [required]
        otp-version: 24 # Define the OTP version [required]
    
    - name: Get deps, and Run tests
      run: |
           mix deps.get
           mix still.compile 

    - name: Add CNAME
      run: echo "blog.shiryel.com" > _site/CNAME

    - name: Remove the trash of jekyll missing the files :)
      run: touch _site/.nojekyll

    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
